services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 65535:65535
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: "host"
